name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: |
          cd frontend
          npm ci --no-audit --no-fund
      - name: Run tests
        run: |
          cd frontend
          npm test -- --watch=false || true
      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/prontivus-frontend:sha-${{ github.sha }} -f frontend/Dockerfile .
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}/prontivus-frontend:sha-${{ github.sha }}
          docker tag ghcr.io/${{ github.repository }}/prontivus-frontend:sha-${{ github.sha }} ghcr.io/${{ github.repository }}/prontivus-frontend:latest
          docker push ghcr.io/${{ github.repository }}/prontivus-frontend:latest


